name: Linting CI

on:
  pull_request:
    branches:
      - develop

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install linters
        run: |
          npm install --no-audit --no-fund --save-dev htmlhint stylelint stylelint-config-standard

      - name: Lint HTML files
        run: npx htmlhint "/*.html" --config .htmlhintrc.json

      - name: Lint CSS files
        run: npx stylelint "/*.css" --config .stylelintrc.json